## Laboratorio 2 - Desarrollo

__1.Generar el dataframe a partir de la lista de listas__

In [1]:
import pandas as pd

# estas son columnas:
#listas de columnas
codigo=[20192010,20182122,20141001,20138871,20151022,20159331,20199431,20146615,20198661,20130121,20181176,
        20167455,20192129,20183312,20162231,20182991,20173381,20199176,20181128,20182712,20182126]
carrera_academica=["Psicologia","Ingieneria de Sistemas","Psicologia","Psicologia","Ingieneria de Sistemas",
                   "Estadistica","Estadistica","Psicologia","Ingieneria de Sistemas","Psicologia","Psicologia",
                   "Ingieneria de Sistemas","Estadistica","Estadistica","Psicologia","Ingieneria de Sistemas",
                   "Psicologia","Psicologia","Ingieneria de Sistemas","Estadistica","Estadistica"]
nacionalidad=["Peruano(a)","Chileno(a)","Peruano(a)","Peruano(a)","Ecuatoriano(a)","Venezolano(a)","Peruano(a)",
              "Venezolano(a)","Peruano(a)","Peruano(a)","Ecuatoriano(a)","Venezolano(a)","Peruano(a)","Peruano(a)",
              "Ecuatoriano(a)","Peruano(a)","Peruano(a)","Boliviano(a)","Peruano(a)","Peruano(a)","Peruano(a)"]
genero=["Femenino","Femenino","Masculino","Femenino","Masculino","Masculino","Femenino","Masculino","Masculino",
        "Femenino","Femenino","Femenino","Femenino","Masculino","Masculino","Masculino","Femenino","Femenino",
        "Femenino","Masculino","Masculino"]
universidad=[1,1,0,1,1,0,0,0,1,0,1,1,0,0,1,0,0,1,0,1,0]
plan_pago=["Pago Unico","Pago por dos cuotas","Pago por tres cuotas","Pago por tres cuotas","Pago por dos cuotas",
           "Pago Unico","Pago Unico","Pago Unico","Pago por dos cuotas","Pago por dos cuotas","Pago por dos cuotas",
           "Pago por tres cuotras","Pago por tres cuotras","Pago por tres cuotras","Pago Unico","Pago por 3 cuotas",
           "Pago por dos cuotas","Pago Unico","Pago Unico","Pago por dos cuotas","Pago por dos cuotas"]
tipo_pago=["Tarjeta","Tarjeta","Efectivo","Efectivo","Tarjeta","Tarjeta","Efectivo","Efectivo","Efectivo",
           "Tarjeta","Tarjeta","Efectivo","Efectivo","Efectivo","Tarjeta","Tarjeta","Efectivo","Efectivo",
           "Efectivo","Tarjeta","Efectivo"]

In [2]:
listOfRows=[codigo,carrera_academica,nacionalidad,genero,universidad,plan_pago,tipo_pago]
listOfRows

[[20192010,
  20182122,
  20141001,
  20138871,
  20151022,
  20159331,
  20199431,
  20146615,
  20198661,
  20130121,
  20181176,
  20167455,
  20192129,
  20183312,
  20162231,
  20182991,
  20173381,
  20199176,
  20181128,
  20182712,
  20182126],
 ['Psicologia',
  'Ingieneria de Sistemas',
  'Psicologia',
  'Psicologia',
  'Ingieneria de Sistemas',
  'Estadistica',
  'Estadistica',
  'Psicologia',
  'Ingieneria de Sistemas',
  'Psicologia',
  'Psicologia',
  'Ingieneria de Sistemas',
  'Estadistica',
  'Estadistica',
  'Psicologia',
  'Ingieneria de Sistemas',
  'Psicologia',
  'Psicologia',
  'Ingieneria de Sistemas',
  'Estadistica',
  'Estadistica'],
 ['Peruano(a)',
  'Chileno(a)',
  'Peruano(a)',
  'Peruano(a)',
  'Ecuatoriano(a)',
  'Venezolano(a)',
  'Peruano(a)',
  'Venezolano(a)',
  'Peruano(a)',
  'Peruano(a)',
  'Ecuatoriano(a)',
  'Venezolano(a)',
  'Peruano(a)',
  'Peruano(a)',
  'Ecuatoriano(a)',
  'Peruano(a)',
  'Peruano(a)',
  'Boliviano(a)',
  'Peruano(a)',
  'Peruano(a)',
  'Peruano(a)'],
 ['Femenino',
  'Femenino',
  'Masculino',
  'Femenino',
  'Masculino',
  'Masculino',
  'Femenino',
  'Masculino',
  'Masculino',
  'Femenino',
  'Femenino',
  'Femenino',
  'Femenino',
  'Masculino',
  'Masculino',
  'Masculino',
  'Femenino',
  'Femenino',
  'Femenino',
  'Masculino',
  'Masculino'],
 [1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0],
 ['Pago Unico',
  'Pago por dos cuotas',
  'Pago por tres cuotas',
  'Pago por tres cuotas',
  'Pago por dos cuotas',
  'Pago Unico',
  'Pago Unico',
  'Pago Unico',
  'Pago por dos cuotas',
  'Pago por dos cuotas',
  'Pago por dos cuotas',
  'Pago por tres cuotras',
  'Pago por tres cuotras',
  'Pago por tres cuotras',
  'Pago Unico',
  'Pago por 3 cuotas',
  'Pago por dos cuotas',
  'Pago Unico',
  'Pago Unico',
  'Pago por dos cuotas',
  'Pago por dos cuotas'],
 ['Tarjeta',
  'Tarjeta',
  'Efectivo',
  'Efectivo',
  'Tarjeta',
  'Tarjeta',
  'Efectivo',
  'Efectivo',
  'Efectivo',
  'Tarjeta',
  'Tarjeta',
  'Efectivo',
  'Efectivo',
  'Efectivo',
  'Tarjeta',
  'Tarjeta',
  'Efectivo',
  'Efectivo',
  'Efectivo',
  'Tarjeta',
  'Efectivo']]

   __Generando el dataFrame__

In [3]:
df=pd.DataFrame(zip(*listOfRows),
                      columns=['Codigo','Carrera Academica','Nacionalidad','Genero','Universidad','Plan de Pago','Tipo de Pago'])
df

,Codigo,Carrera Academica,Nacionalidad,Genero,Universidad,Plan de Pago,Tipo de Pago
0,20192010,Psicologia,Peruano(a),Femenino,1,Pago Unico,Tarjeta
1,20182122,Ingieneria de Sistemas,Chileno(a),Femenino,1,Pago por dos cuotas,Tarjeta
2,20141001,Psicologia,Peruano(a),Masculino,0,Pago por tres cuotas,Efectivo
3,20138871,Psicologia,Peruano(a),Femenino,1,Pago por tres cuotas,Efectivo
4,20151022,Ingieneria de Sistemas,Ecuatoriano(a),Masculino,1,Pago por dos cuotas,Tarjeta
5,20159331,Estadistica,Venezolano(a),Masculino,0,Pago Unico,Tarjeta
6,20199431,Estadistica,Peruano(a),Femenino,0,Pago Unico,Efectivo
7,20146615,Psicologia,Venezolano(a),Masculino,0,Pago Unico,Efectivo
8,20198661,Ingieneria de Sistemas,Peruano(a),Masculino,1,Pago por dos cuotas,Efectivo
9,20130121,Psicologia,Peruano(a),Femenino,0,Pago por dos cuotas,Tarjeta
10,20181176,Psicologia,Ecuatoriano(a),Femenino,1,Pago por dos cuotas,Tarjeta
11,20167455,Ingieneria de Sistemas,Venezolano(a),Femenino,1,Pago por tres cuotras,Efectivo
12,20192129,Estadistica,Peruano(a),Femenino,0,Pago por tres cuotras,Efectivo
13,20183312,Estadistica,Peruano(a),Masculino,0,Pago por tres cuotras,Efectivo
14,20162231,Psicologia,Ecuatoriano(a),Masculino,1,Pago Unico,Tarjeta
15,20182991,Ingieneria de Sistemas,Peruano(a),Masculino,0,Pago por 3 cuotas,Tarjeta
16,20173381,Psicologia,Peruano(a),Femenino,0,Pago por dos cuotas,Efectivo
17,20199176,Psicologia,Boliviano(a),Femenino,1,Pago Unico,Efectivo
18,20181128,Ingieneria de Sistemas,Peruano(a),Femenino,0,Pago Unico,Efectivo
19,20182712,Estadistica,Peruano(a),Masculino,1,Pago por dos cuotas,Tarjeta
20,20182126,Estadistica,Peruano(a),Masculino,0,Pago por dos cuotas,Efectivo

__2.Encontrar los alumnos con genero "femenino"__

In [4]:
df.loc[df['Genero']=='Femenino']

,Codigo,Carrera Academica,Nacionalidad,Genero,Universidad,Plan de Pago,Tipo de Pago
0,20192010,Psicologia,Peruano(a),Femenino,1,Pago Unico,Tarjeta
1,20182122,Ingieneria de Sistemas,Chileno(a),Femenino,1,Pago por dos cuotas,Tarjeta
3,20138871,Psicologia,Peruano(a),Femenino,1,Pago por tres cuotas,Efectivo
6,20199431,Estadistica,Peruano(a),Femenino,0,Pago Unico,Efectivo
9,20130121,Psicologia,Peruano(a),Femenino,0,Pago por dos cuotas,Tarjeta
10,20181176,Psicologia,Ecuatoriano(a),Femenino,1,Pago por dos cuotas,Tarjeta
11,20167455,Ingieneria de Sistemas,Venezolano(a),Femenino,1,Pago por tres cuotras,Efectivo
12,20192129,Estadistica,Peruano(a),Femenino,0,Pago por tres cuotras,Efectivo
16,20173381,Psicologia,Peruano(a),Femenino,0,Pago por dos cuotas,Efectivo
17,20199176,Psicologia,Boliviano(a),Femenino,1,Pago Unico,Efectivo
18,20181128,Ingieneria de Sistemas,Peruano(a),Femenino,0,Pago Unico,Efectivo

__3. La alumna con mayor tiempo dentro del curso IEEE.__

In [5]:
df.loc[df['Codigo'].idxmin()]

Codigo                          20130121
Carrera Academica             Psicologia
Nacionalidad                  Peruano(a)
Genero                          Femenino
Universidad                            0
Plan de Pago         Pago por dos cuotas
Tipo de Pago                     Tarjeta
Name: 9, dtype: object

__4.Las alumnas con codigo a partir del año 2019 en adelante que no sean del sexo femenino__

In [6]:
df.loc[(df['Codigo']>=20190000) & (df['Genero']!='Femenino')]

,Codigo,Carrera Academica,Nacionalidad,Genero,Universidad,Plan de Pago,Tipo de Pago
8,20198661,Ingieneria de Sistemas,Peruano(a),Masculino,1,Pago por dos cuotas,Efectivo